version: 0.2

phases:
  pre_build:
    commands:
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - npm install
      - $(aws ecr get-login --no-include-email --region $AWS_REGION)
      - REPOSITORY_URI=207880003428.dkr.ecr.ap-south-1.amazonaws.com/nodejs-docker-medium
  build:
    commands:
      - echo Building application
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - docker push $REPOSITORY_URI:latest
      - echo Writing image definitions file...
      - printf '{"ImageURI":"%s"}' $REPOSITORY_URI:$IMAGE_TAG > imageDetails.json
      - cat imageDetails.json
artifacts:
    files: 
      - imageDetails.json
      - appspec.yaml
      - taskdef.json
cache:
    paths:
      - ~/.npm
      - /var/lib/docker/**/*
